import { CheckCircle2, MessageSquareText } from "lucide-react"
import { headers } from "next/headers"
import { notFound, redirect } from "next/navigation"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { markFeedbackAddressed } from "@/features/student-feedback/actions"
import { FeedbackResponseForm } from "@/features/student-feedback/components/feedback-response-form"
import { getStudentFeedback } from "@/features/student-feedback/repositories/student-feedback-repository"
import { UserRole } from "@/generated/prisma/client"
import { getServerSession } from "@/lib/server-session"
function date(value: Date) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(value) }
export default async function StudentFeedbackPage() { const session = await getServerSession(await headers()); if (!session) redirect("/auth?mode=sign-in"); if (session.user.role !== UserRole.STUDENT) notFound(); const items = await getStudentFeedback(session.user.id); return <main className="mx-auto w-full max-w-5xl space-y-6 p-4 sm:p-6 lg:p-8"><div><h1 className="font-heading text-2xl font-semibold">Supervisor feedback</h1><p className="mt-1 text-sm text-muted-foreground">Review comments, respond, and mark completed changes as addressed.</p></div><Card><CardHeader className="border-b"><CardTitle>Feedback inbox</CardTitle><CardDescription>{items.filter((item) => !item.resolvedAt).length} item(s) awaiting action</CardDescription></CardHeader><CardContent className="divide-y p-0">{items.length === 0 ? <div className="grid min-h-72 place-items-center text-center"><div><MessageSquareText className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 text-sm font-medium">No feedback yet</p><p className="mt-1 text-xs text-muted-foreground">Supervisor comments will appear here.</p></div></div> : items.map((feedback) => <article key={feedback.id} className="p-4 sm:p-5"><div className="flex gap-3"><Avatar>{feedback.author.image ? <AvatarImage src={feedback.author.image} alt={feedback.author.name} /> : null}<AvatarFallback>{feedback.author.name.charAt(0)}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-semibold">{feedback.project.title}</p><p className="text-[10px] text-muted-foreground">{feedback.author.name} · {date(feedback.createdAt)}</p></div><span className={`rounded-full px-2 py-0.5 text-[10px] ${feedback.resolvedAt ? "bg-primary/10 text-primary" : "bg-accent text-accent-foreground"}`}>{feedback.resolvedAt ? "Addressed" : "Action needed"}</span></div><p className="mt-3 whitespace-pre-wrap rounded-md border bg-muted/20 p-3 text-xs">{feedback.body}</p>{feedback.replies.length > 0 ? <div className="mt-3 space-y-2">{feedback.replies.map((reply) => <div key={reply.id} className="rounded-md border-l-2 border-l-primary bg-primary/5 p-3"><p className="text-[10px] font-medium">{reply.author.id === session.user.id ? "You" : reply.author.name} · {date(reply.createdAt)}</p><p className="mt-1 text-xs">{reply.body}</p></div>)}</div> : null}{!feedback.resolvedAt ? <><FeedbackResponseForm feedbackId={feedback.id} /><form action={async () => { "use server"; await markFeedbackAddressed({ feedbackId: feedback.id }) }} className="mt-2"><Button variant="outline" size="sm"><CheckCircle2 />Mark addressed</Button></form></> : null}</div></div></article>)}</CardContent></Card></main> }
