"use client"
import { ArrowLeft, Archive, Loader2 } from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { type FormEvent, useState, useTransition } from "react"
import { toast } from "react-toastify"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { addPastProject } from "../actions"
import type { PublishableProject } from "../types"

export function AddPastProjectForm({ projects }: { projects: PublishableProject[] }) {
  const available = projects.filter((project) => !project.alreadyPublished); const [projectId, setProjectId] = useState(available[0]?.id ?? ""); const [year, setYear] = useState(new Date().getFullYear()); const [technologies, setTechnologies] = useState(""); const [externalUrl, setExternalUrl] = useState(""); const [pending, startTransition] = useTransition(); const router = useRouter()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); startTransition(async () => { const result = await addPastProject({ projectId, year, technologies: technologies.split(",").map((value) => value.trim()).filter(Boolean), externalUrl }); if (!result.success) { toast.error(result.error); return }; toast.success("Past project added to the repository."); router.push("/student/repository?type=PAST_PROJECT") }) }
  return <main className="mx-auto w-full max-w-2xl space-y-5 p-4 sm:p-6 lg:p-8"><Button variant="ghost" size="sm" asChild><Link href="/student/repository"><ArrowLeft /> Repository</Link></Button><Card><CardHeader><CardTitle>Add a past project</CardTitle><CardDescription>Publish one of your projects to your institution’s research repository. Its current PDF report will remain available for download.</CardDescription></CardHeader><CardContent>{available.length ? <form className="space-y-4" onSubmit={submit}><label className="block text-xs font-medium">Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="mt-1 h-9 w-full border border-input bg-background px-3 text-sm" required>{available.map((project) => <option key={project.id} value={project.id}>{project.title} ({project.status.toLowerCase().replaceAll("_", " ")})</option>)}</select></label><label className="block text-xs font-medium">Completion year<Input className="mt-1" type="number" min={1900} max={new Date().getFullYear()} value={year} onChange={(event) => setYear(Number(event.target.value))} required /></label><label className="block text-xs font-medium">Technologies or methods<Input className="mt-1" value={technologies} onChange={(event) => setTechnologies(event.target.value)} placeholder="Next.js, surveys, machine learning" /><span className="mt-1 block text-[10px] text-muted-foreground">Separate entries with commas. Project keywords are used if left empty.</span></label><label className="block text-xs font-medium">External project URL (optional)<Input className="mt-1" type="url" value={externalUrl} onChange={(event) => setExternalUrl(event.target.value)} placeholder="https://github.com/..." /></label><Button className="w-full" disabled={pending || !projectId}>{pending ? <Loader2 className="animate-spin" /> : <Archive />}{pending ? "Publishing..." : "Add to repository"}</Button></form> : <div className="py-12 text-center"><Archive className="mx-auto size-10 text-muted-foreground" /><p className="mt-3 text-sm font-medium">No projects available</p><p className="mt-1 text-xs text-muted-foreground">Create a project first, or all your projects are already published.</p><Button className="mt-4" variant="outline" asChild><Link href="/student/projects">View projects</Link></Button></div>}</CardContent></Card></main>
}
