"use client"
import { Bot, Loader2, Send, X } from "lucide-react"
import { type FormEvent, useEffect, useRef, useState, useTransition } from "react"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { chatWithPastProject } from "../actions"

type Message = { id: string; role: "user" | "assistant"; content: string }
export function RepositoryChatbot({ initialConversationId, initialMessages, user }: { initialConversationId: string | null; initialMessages: Message[]; user: { name: string; image: string | null } }) {
  const welcome: Message = { id: "welcome", role: "assistant", content: "Hello! Ask me about any past project, research paper, or capstone report in your institution’s repository." }
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>(initialMessages.length ? initialMessages : [welcome]); const [conversationId, setConversationId] = useState<string | null>(initialConversationId); const [prompt, setPrompt] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const end = useRef<HTMLDivElement>(null)
  useEffect(() => {
    end.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages, pending])
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const question = prompt.trim(); if (!question) return; setPrompt(""); setError(null); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "user", content: question }]); startTransition(async () => { const result = await chatWithPastProject({ conversationId, prompt: question }); if (!result.success) { setError(result.error); return }; setConversationId(result.data.conversationId); setMessages((current) => [...current, result.data.message]) }) }
  if (!open) return <Button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-50 size-14 rounded-full shadow-xl" size="icon" aria-label="Open repository assistant"><Bot className="size-6" /></Button>
  return <aside className="fixed inset-x-3 bottom-3 z-50 flex max-h-[min(680px,calc(100vh-1.5rem))] flex-col overflow-hidden rounded-xl border bg-card shadow-2xl sm:inset-x-auto sm:right-5 sm:w-[390px]" aria-label="Repository assistant"><header className="flex items-center gap-3 border-b bg-primary px-4 py-3 text-primary-foreground"><span className="grid size-9 place-items-center rounded-full bg-primary-foreground/15"><Bot className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold">Repository assistant</p><p className="truncate text-[10px] opacity-80">All projects, papers, and reports</p></div><Button variant="ghost" size="icon-sm" className="text-primary-foreground hover:bg-primary-foreground/15 hover:text-primary-foreground" onClick={() => setOpen(false)} aria-label="Close chat"><X /></Button></header><div className="min-h-72 flex-1 space-y-4 overflow-y-auto bg-muted/30 p-4">{messages.map((message) => <div key={message.id} className={cn("flex items-end gap-2", message.role === "user" && "flex-row-reverse")}><Avatar size="sm" className="shrink-0">{message.role === "user" && user.image ? <AvatarImage src={user.image} alt={user.name} /> : null}<AvatarFallback className={cn(message.role === "assistant" && "bg-primary text-primary-foreground")}>{message.role === "assistant" ? <Bot className="size-3.5" /> : user.name.slice(0, 2).toUpperCase()}</AvatarFallback></Avatar><div className={cn("max-w-[78%] rounded-xl px-3 py-2 text-xs leading-5", message.role === "user" ? "bg-primary text-primary-foreground" : "border bg-card text-card-foreground")}>{message.content}</div></div>)}{pending ? <div className="flex items-end gap-2"><Avatar size="sm"><AvatarFallback className="bg-primary text-primary-foreground"><Bot className="size-3.5" /></AvatarFallback></Avatar><span className="inline-flex items-center gap-2 rounded-xl border bg-card px-3 py-2 text-xs text-muted-foreground"><Loader2 className="size-3.5 animate-spin" /> Searching the repository…</span></div> : null}<div ref={end} /></div><form onSubmit={submit} className="border-t bg-card p-3">{error ? <p className="mb-2 text-[10px] text-destructive">{error}</p> : null}<div className="flex gap-2"><Input value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ask about repository research…" disabled={pending} maxLength={4000} aria-label="Question about repository" /><Button type="submit" size="icon" disabled={pending || prompt.trim().length < 2} aria-label="Send question"><Send /></Button></div></form></aside>
}
